"""Login flow for the DeepVista CLI.

Two flows:

  1. Local callback (default, interactive):
     CLI starts localhost server → browser POSTs tokens back.

  2. Short code (non-interactive):
     User visits /cli in browser, gets a one-time code,
     runs `deepvista auth login --code XXXX-XXXX`.
     CLI exchanges the code for tokens via the API.
"""

from __future__ import annotations

import os
import time
from pathlib import Path

import click
import httpx

from deepvista_cli.auth.callback_server import login_with_callback
from deepvista_cli.auth.tokens import TokenSet, _extract_issuer, save_tokens


def _can_open_browser() -> bool:
    """Heuristic: can we reasonably expect a browser to open?

    Returns False in SSH sessions, containers, CI, and other headless
    environments where ``webbrowser.open`` would silently fail.
    """
    if os.environ.get("SSH_CONNECTION") or os.environ.get("SSH_TTY"):
        return False
    if os.environ.get("GITHUB_ACTIONS") or os.environ.get("CI"):
        return False
    if os.environ.get("CODESPACES"):
        return False
    if Path("/.dockerenv").exists():
        return False

    if os.name == "posix" and not os.environ.get("DISPLAY") and not os.environ.get("WAYLAND_DISPLAY"):
        import platform

        if platform.system() != "Darwin":
            return False

    return True


def login_auto(
    auth_url: str = "https://app.deepvista.ai",
    credentials_path: Path | None = None,
) -> TokenSet:
    """Auto-detect the best login flow and run it.

    Uses local callback when a browser is available, otherwise prints
    instructions for the user to visit /cli manually.
    """
    if _can_open_browser():
        return login_with_callback(auth_url, credentials_path)

    # Headless — instruct user to visit /cli and use --code
    login_url = f"{auth_url}/cli"
    click.echo("", err=True)
    click.echo("  No browser detected. To authenticate:", err=True)
    click.echo(f"  1. Visit {login_url} on any device", err=True)
    click.echo("  2. Sign in and copy the command shown", err=True)
    click.echo("  3. Paste it here (e.g. deepvista auth login --code XXXX-XXXX)", err=True)
    click.echo("", err=True)
    raise SystemExit(0)


def login_with_code(
    code: str,
    auth_url: str = "https://app.deepvista.ai",
    credentials_path: Path | None = None,
) -> TokenSet:
    """Exchange a one-time short code for session tokens via the API.

    The code (e.g. ABCD-1234) was generated by /cli after the user
    authenticated in the browser. It's single-use and expires in 10 minutes.
    """
    code = code.strip().upper()

    try:
        resp = httpx.post(
            f"{auth_url}/api/auth/device/token",
            json={"user_code": code},
            timeout=15,
        )
    except httpx.ConnectError:
        raise click.ClickException(f"Cannot reach {auth_url}. Check your connection and try again.")

    if resp.status_code == 404:
        raise click.ClickException("Invalid code. Make sure you copied it correctly from the browser.")

    if resp.status_code == 410:
        raise click.ClickException("Code has expired. Visit /cli again to get a new one.")

    if resp.status_code != 200:
        raise click.ClickException(f"Authentication failed: {resp.text}")

    data = resp.json()

    if "access_token" not in data:
        raise click.ClickException("Unexpected response from server. Please try again.")

    user = data.get("user", {})
    access_token = data["access_token"]
    tokens = TokenSet(
        access_token=access_token,
        refresh_token=data.get("refresh_token", ""),
        expires_at=float(data.get("expires_at", time.time() + 3600)),
        user_id=user.get("id", ""),
        email=user.get("email", ""),
        issuer=_extract_issuer(access_token) or "",
        api_key=data.get("api_key", ""),
    )
    save_tokens(tokens, credentials_path)
    return tokens
